/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavorecidosRouteImport } from './routes/favorecidos'
import { Route as DespesaRouteImport } from './routes/despesa'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RelatoriosIndexRouteImport } from './routes/relatorios.index'
import { Route as RelatoriosDespesasRouteImport } from './routes/relatorios.despesas'

const FavorecidosRoute = FavorecidosRouteImport.update({
  id: '/favorecidos',
  path: '/favorecidos',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesaRoute = DespesaRouteImport.update({
  id: '/despesa',
  path: '/despesa',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosIndexRoute = RelatoriosIndexRouteImport.update({
  id: '/relatorios/',
  path: '/relatorios/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosDespesasRoute = RelatoriosDespesasRouteImport.update({
  id: '/relatorios/despesas',
  path: '/relatorios/despesas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/categorias': typeof CategoriasRoute
  '/despesa': typeof DespesaRoute
  '/favorecidos': typeof FavorecidosRoute
  '/relatorios/despesas': typeof RelatoriosDespesasRoute
  '/relatorios/': typeof RelatoriosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/categorias': typeof CategoriasRoute
  '/despesa': typeof DespesaRoute
  '/favorecidos': typeof FavorecidosRoute
  '/relatorios/despesas': typeof RelatoriosDespesasRoute
  '/relatorios': typeof RelatoriosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/categorias': typeof CategoriasRoute
  '/despesa': typeof DespesaRoute
  '/favorecidos': typeof FavorecidosRoute
  '/relatorios/despesas': typeof RelatoriosDespesasRoute
  '/relatorios/': typeof RelatoriosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/categorias'
    | '/despesa'
    | '/favorecidos'
    | '/relatorios/despesas'
    | '/relatorios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/categorias'
    | '/despesa'
    | '/favorecidos'
    | '/relatorios/despesas'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/categorias'
    | '/despesa'
    | '/favorecidos'
    | '/relatorios/despesas'
    | '/relatorios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  CategoriasRoute: typeof CategoriasRoute
  DespesaRoute: typeof DespesaRoute
  FavorecidosRoute: typeof FavorecidosRoute
  RelatoriosDespesasRoute: typeof RelatoriosDespesasRoute
  RelatoriosIndexRoute: typeof RelatoriosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favorecidos': {
      id: '/favorecidos'
      path: '/favorecidos'
      fullPath: '/favorecidos'
      preLoaderRoute: typeof FavorecidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesa': {
      id: '/despesa'
      path: '/despesa'
      fullPath: '/despesa'
      preLoaderRoute: typeof DespesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/': {
      id: '/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof RelatoriosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/despesas': {
      id: '/relatorios/despesas'
      path: '/relatorios/despesas'
      fullPath: '/relatorios/despesas'
      preLoaderRoute: typeof RelatoriosDespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  CategoriasRoute: CategoriasRoute,
  DespesaRoute: DespesaRoute,
  FavorecidosRoute: FavorecidosRoute,
  RelatoriosDespesasRoute: RelatoriosDespesasRoute,
  RelatoriosIndexRoute: RelatoriosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
