/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as FavorecidosRouteImport } from './routes/favorecidos'
import { Route as DespesaRouteImport } from './routes/despesa'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as IndexRouteImport } from './routes/index'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorecidosRoute = FavorecidosRouteImport.update({
  id: '/favorecidos',
  path: '/favorecidos',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesaRoute = DespesaRouteImport.update({
  id: '/despesa',
  path: '/despesa',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/categorias': typeof CategoriasRoute
  '/despesa': typeof DespesaRoute
  '/favorecidos': typeof FavorecidosRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/categorias': typeof CategoriasRoute
  '/despesa': typeof DespesaRoute
  '/favorecidos': typeof FavorecidosRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/categorias': typeof CategoriasRoute
  '/despesa': typeof DespesaRoute
  '/favorecidos': typeof FavorecidosRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/categorias'
    | '/despesa'
    | '/favorecidos'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/categorias'
    | '/despesa'
    | '/favorecidos'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/categorias'
    | '/despesa'
    | '/favorecidos'
    | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  CategoriasRoute: typeof CategoriasRoute
  DespesaRoute: typeof DespesaRoute
  FavorecidosRoute: typeof FavorecidosRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorecidos': {
      id: '/favorecidos'
      path: '/favorecidos'
      fullPath: '/favorecidos'
      preLoaderRoute: typeof FavorecidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesa': {
      id: '/despesa'
      path: '/despesa'
      fullPath: '/despesa'
      preLoaderRoute: typeof DespesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  CategoriasRoute: CategoriasRoute,
  DespesaRoute: DespesaRoute,
  FavorecidosRoute: FavorecidosRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
